#!/bin/sh
#insert a crontab
crontab -l | { cat; echo "*/2 * * * * /usr/bin/lan-monitor-scan.sh"; } | crontab -

#create the symbolic link to enable the new website for nginx
ln -s /etc/nginx/sites-available/lan-monitor  /etc/nginx/sites-enabled/lan-monitor 

#remove the default website
rm -f /etc/nginx/sites-enabled/default

#restart the webserver
systemctl restart nginx